---
language: objective-c

matrix:
  fast_finish:
    true
  include:
    - os:
        osx
      osx_image:
        xcode9
    - os:
        osx
      osx_image:
        xcode9.1
    - os:
        osx
      osx_image:
        xcode9.2

# before_install:
#   - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/derphilipp
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/derphilipp/homebrew-sublercli
script:
  - brew install sublercli --HEAD --verbose
  - brew audit sublercli --strict --except=specs
  - brew test sublercli
  - SublerCLI -version
